version: '3.8'
services:
  broker:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/code
    working_dir: /code
    entrypoint: ["/bin/cloud-service-broker"]
    command: ["serve"]
    depends_on:
      - database
    restart: on-failure
    environment:
      DB_HOST: database
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      SECURITY_USER_NAME: user
      SECURITY_USER_PASSWORD: pass
      GSB_API_HOSTNAME: broker
      PORT: 80
    env_file:
    - .env.secrets

  database:
    image: mysql:latest
    volumes:
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: servicebroker

volumes:
  database_data:
