---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-solr8
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-solr8
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-solr8
    spec:
      containers:
      - image: solr:8.11
        imagePullPolicy: Always
        name: app-solr8
        env:
        - name: SOLR_JAVA_MEM
          value: "-Xms7g -Xmx10g"
        resources:
          requests:
            memory: "14G"
            cpu: "2500m"
        ports:
        - containerPort: 8983
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/solr/data
      initContainers:
      - name: download-setup-script
        image: busybox:1.28
        command:
        - wget
        - "-O"
        - "/var/solr/data/solr-auth-setup.sh"
        - https://gist.githubusercontent.com/FuhuXia/91cac09b23ef29e5f219ba83df8b808e/raw/76de04dd7edf0faef2c04d8a8bbd51ee2cef237f/solr-setup-for-catalog.sh
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/solr/data
      - name: run-setup-script
        image: busybox:1.28
        command:
        - sh
        - /var/solr/data/solr-auth-setup.sh
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/solr/data
      securityContext:
        fsGroup: 8983
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim
      
---
apiVersion: v1
kind: Service
metadata:
  name: service-solr8
spec:
  ports:
    - port: 80
      targetPort: 8983
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-solr8
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-solr8
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-solr8
            port: 
              number: 80              
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 35Gi