# On pull request events, this workflow will run `make build-and-test`. 
# On push events to the main branch, this workflow will upload a date-named release 

name: 'Test and (Maybe) Release'

on:
  push:
    branches:
    - 'main'
  pull_request:

jobs:
  make:
    name: 'Make'
    runs-on: ubuntu-latest
    env:
      # For storing the Terraform state for the deployment
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_DEFAULT_REGION: "${{ secrets.AWS_DEFAULT_REGION }}"

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

    - name: Supply an empty .env.secrets file
      run: |
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > .env.secrets
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env.secrets
        echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env.secrets

    - name: Authenticate with the GitHub Package Registry
      run: docker login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com

    - name: Build and run examples (tests)
      run: make build

    - name: Run examples (tests)
      # Since they're expensive, only run tests on branches; main is redundant
      if: github.ref != 'refs/heads/main'
      run: make up && make test && make down

    - name: Bump version and push tag
      id: bump
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 0.0.0

    - name: Release pushes to main
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.brokerpak
        tag_name: ${{ steps.bump.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

