# When a tag is pushed, create a tag-named release with the brokerpak in it 
name: 'release'
on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:  
    - name: Install the eden OSBAPI CLI tool
      run: |
        wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | sudo apt-key add -
        echo "deb http://apt.starkandwayne.com stable main" | sudo tee /etc/apt/sources.list.d/starkandwayne.list
        sudo apt-get update
        sudo apt-get install eden
    - name: Check out repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

    - name: Build the brokerpak
      run: make build

    - name: Rename the brokerpak file based on the tag
      run: mv eks-services-pak-current.brokerpak eks-services-pak-${GITHUB_REF#refs/*/}.brokerpak

    - name: Create a release and upload the files
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.brokerpak"
        artifactErrorsFailBuild: true
        token: ${{ secrets.GITHUB_TOKEN }}      
